### ISSUE TITLE
Please add a section for character details and/or description on the character sheets

### ISSUE THREAD

**Issue by PeterChernoff** [sheibeck/fcs#37]
I think it's a bit weird that there's no place for you to enter character details. Even if it would be on a different page, people generally like having the ability to fill out that part of a character sheet.

**Comment by sheibeck** [comment]
Hi, Peter. My goal here was to reproduce the sheets as closely as possible to the official versions. Most of them don't have a description, mainly because the character aspects should describe a character well enough that an actual description field generally isn't needed.

With that being said, could you let me know which sheet specifically you would like this on?

**Comment by PeterChernoff** [comment]
I mean, it would be nice to have that in general, but I'm currently using Fate Condensed,

Maybe have an option (like a toggle that would allow you to add Extras, Descriptions and History?

**Comment by sheibeck** [comment]
I hear you. I put it on the list. Thanks for the feedback!

**Comment by PeterChernoff** [comment]
No problem. Thanks for listening.
